name: 反馈问题
description: 请告诉我们你遇到的问题
title: "[Bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        > 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。
        >
        > [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

  - type: markdown
    attributes:
      value: "**反馈须知**\n\n⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。"

  - type: checkboxes
    id: acknowledgement
    attributes:
      label: "请确认以下信息"
      description: "请在下方中括号内输入 x 来表示你已经知晓相关内容。"
      options:
        - label: "我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；"
        - label: "我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。"
        - label: "我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。"

  - type: textarea
    id: problem-description
    attributes:
      label: "描述问题"
      description: "请在此描述你遇到了什么问题。"
      placeholder: "详细描述遇到的问题..."
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: "如何复现"
      description: "请告诉我们你是通过什么操作触发的该问题。"
      placeholder: "步骤 1, 步骤 2, 步骤 3..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "截图"
      description: "请在此提供控制台截图、屏幕截图或者服务端的 log 截图。"
      placeholder: "你可以将图片拖放到这里或使用 Markdown 语法插入。"
    validations:
      required: false

  - type: input
    id: system
    attributes:
      label: "系统"
      description: "你的操作系统。"
      placeholder: "比如 windows 10/ macos 12/ linux / android 11 / ios 16"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: "浏览器"
      description: "你使用的浏览器。"
      placeholder: "比如 chrome, safari"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "版本"
      description: "填写设置页面的版本号。"
      placeholder: "例如：1.2.3"
    validations:
      required: true

  - type: dropdown
    id: deployment-method
    attributes:
      label: "部署方式"
      description: "请选择你的部署方式。"
      options:
        - vercel
        - docker
        - 服务器部署
    validations:
      required: true
